version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Reactivities.API/Dockerfile
    container_name: backend
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
