SELECT TOP (1000)
    [Id]
      , [DisplayName]
      , [Bio]
      , [ImageUrl]
      , [UserName]
      , [NormalizedUserName]
      , [Email]
      , [NormalizedEmail]
      , [EmailConfirmed]
      , [PasswordHash]
      , [SecurityStamp]
      , [ConcurrencyStamp]
      , [PhoneNumber]
      , [PhoneNumberConfirmed]
      , [TwoFactorEnabled]
      , [LockoutEnd]
      , [LockoutEnabled]
      , [AccessFailedCount]
FROM [reactivities-project].[dbo].AspNetUsers